# Site settings
title: Tanguy HODONOU
general_email: tanguy.hodonou@yahoo.com
academic_email: tanguy.hodonou@etu.u-cergy.fr

description: > # this means to ignore newlines until "baseurl:"
  data scientist, data analyst machine learning, data visualization, Python, R, SQL

baseurl: "/tanguyhod.github.io" # the subpath of your site, e.g. /blog/

url: "https://ys1998.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: tanguyhod
#linkedin_username: linkedin_username
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
